### ISSUE TITLE
Sharding.md 의 "4.Altibase Sharding 딕셔너리" 하위 항목들에 대해서 redirect 기능이 동작하지 않습니다.

### ISSUE THREAD

**Issue by junyoungKimGit** [ALTIBASE/Documents#32]
매뉴얼 최상위 Table of Contents 에서 4.Altibase Sharding 하위 항목들의 redirection 기능이 정상동작하지 않습니다.

모든 하위 항목들에 대해서 동작하지 않는 것은 아니며, SYS_ 로 시작하거나 S$로 시작하는 항목들만 동작하지 않습니다.

**Comment by hessalti** [comment]
Issue resolved.
