### ISSUE TITLE
General Reference에 설명된 REPLICATION_SYNC_TUPLE_COUNT 의 설명이 변경되어야 할 것 같습니다.

### ISSUE THREAD

**Issue by hscho-altibase** [ALTIBASE/Documents#4]
Manuals/Altibase_7.1/kor/GeneralReference_2.md에 REPLICATION_SYNC_TUPLE_COUNT의 설명이 아래와 같이 기술되어 있습니다.

"병렬 동기화시 송신 쓰레드가 한번에 읽어서 처리할 수 있는 레코드의 최대 개수를 지정한다."

그런데, Review-12580 내용을 보면, 6.5.1부터 해당 프로퍼티가,  
Sender에서는 페이지 단위로 처리되기 때문에 Sender에서는 별 의미가 없고 
Receiver에서만 의미가 있는 것처럼 보입니다.
그래서, 변경된 기능에 적합하도록 해당 프로퍼티 설명이 수정되어야 할 것 같습니다.

**Comment by hessalti** [comment]
DM팀에서 확인 부탁드립니다.
github을 이용한 매뉴얼관련 이슈처리에 대하여, 아직 정확한 정식절차가 있는것은 아니고, 시범적으로 해보는 것입니다.

**Comment by junyoungKimGit** [comment]
receiver는 sender가 보내주는 xlog를 곧이 곧대로 처리하는 수동적인 동작을 하기 때문에, sender의 관점에서 기록해야 하는 것이 맞습니다. 게다가, 해당 property를 standby 쪽에서 설정하는 것은 아무런 의미가 없습니다. active 쪽에서만 해당 property 값의 영향을 받습니다. sender는 해당 property를 읽고 receiver에서 tuple count 단위로 처리할 수 있게 xlog를 생성합니다.

그리고, sender가 page 단위로 읽는 것은 맞지만, 처리하는 단위는 해당 property에 설정 된 tuple 값 단위로 처리하는 것이 맞기 때문에, property 설명을 수정할 필요는 없어 보입니다.

굳이 수정을 한다면, "병렬 동기화시 송신 쓰레드가 한번에 처리할 수 있는 레코드의 최대 개수를 지정한다." 로  수정하는 편이 좋을 것 같습니다.

**Comment by hessalti** [comment]
Current content need not be changed.
