### ISSUE TITLE
where is license 

### ISSUE THREAD

**Issue by bushro** [ALTIBASE/Documents#50]
where is license

**Comment by hessalti** [comment]
You can download Altibase open edition from here(https://altibase.com/resources/free-download/).
You can use freely Altibase open edition without any license.

**Comment by bushro** [comment]
github上面下载的没有许可证数据库好像创建不了，执行sh post_install.sh dbcreate 有错

**Comment by bushro** [comment]
github上面下载的没有许可证数据库好像创建不了，执行sh post_install.sh dbcreate 有错
github上面下载的没有许可证数据库好像创建不了，执行sh post_install.sh dbcreate 有错
The license free database downloaded from GitHub seems to be unable to be created. Execute sh post_ install.sh Dbcreate is wrong

**Comment by bushro** [comment]
The license free database downloaded from GitHub seems to be unable to be created. Execute sh post_ install.sh Dbcreate is wrong
