### ISSUE TITLE
Replication.md 에 잘못된 구문 설명이 있습니다.

### ISSUE THREAD

**Issue by junyoungKimGit** [ALTIBASE/Documents#73]
Replication.md 의 "이중화 대상 테이블에 DDL 실행" 문단에서

"ALTER TABLE table_name TRUNCATE PARTITION TRUNCATE TABLE table_name;"

구문 syntax가 잘못되었습니다.

=> ALTER TABLE table_name TRUNCATE PARTITION partition_name;
으로 수정되어야 합니다.

**Comment by junyoungKimGit** [comment]
7.1, trunk 두 곳 모두에서 잘못되었습니다.

**Comment by hessalti** [comment]
모두 수정했습니다.
